name: Release
on:
- pull_request
- push
- workflow_dispatch
jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3 # Récupère le contenu du dépôt correspondant au commit du workflow en cours
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
      - name: "Build Image"
        run: docker image build --tag=docker-cicd:latest ./
      - name: "Starting the app"
        run: docker container run -p 8080:8080 --name docker-cicd docker-cicd:latest mvn spring-boot:start
      - name: "Stoping the app"
        run: docker container stop docker-cicd 
