name: Release
on:
- pull_request
- push
jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3 # Récupère le contenu du dépôt correspondant au commit du workflow en cours
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
      - name: "Build Image"
        run: docker image build --tag=docker-cicd:latest ./
      - name: "Doing Test : Maven Clean install"
        run: docker container run docker-cicd:latest mvn clean install
      - name : "Doing Test : Maven Package"
        run: docker container run codcker-cicd:latets mvn package